### ISSUE TITLE
Idempotency broken , creates and removes 'conf.d/stream' directory.

### ISSUE THREAD

**Issue by philipwigg** [jdauphant/ansible-role-nginx#118]
Every time I run Ansible, it creates a ```conf.d/stream``` directory.

```
TASK [nginx : Create the directories for site specific configurations] *********
ok: [agri.dev.ts-new] => (item=sites-available)
ok: [agri.dev.ts-new] => (item=sites-enabled)
ok: [agri.dev.ts-new] => (item=auth_basic)
ok: [agri.dev.ts-new] => (item=conf.d)
changed: [agri.dev.ts-new] => (item=conf.d/stream)
````

but then removes that same ```conf.d/stream``` directory as part of the 'Remove unmanaged config files' step on the same run.

I am using Ansible 2.2.2 and Ubuntu 14.04.

**Comment by jdauphant** [comment]
Thanks for the report, if you have a fix don't hesitate to send a PR

**Comment by philipwigg** [comment]
Cheers.. I'm just testing one now.
