### ISSUE TITLE
How to automatically create a root directory?

### ISSUE THREAD

**Issue by meteorlad** [jdauphant/ansible-role-nginx#125]
How to automatically create a root directory?
example:
 foo:
     - root "/tmp/site1"
 bar:
     - root "/tmp/site2"

How to ensure the above path while creating it?

**Comment by jdauphant** [comment]
You have to ensure path exist outside the role in your playbook before calling the role ( you can use post_tasks for that).
Also I don't know if this will help you but you can use Ansible templating with this role, like that if you have generic site :
https://github.com/jdauphant/ansible-role-nginx/releases/tag/v1.2
