### ISSUE TITLE
Suggestions for using stream config?

### ISSUE THREAD

**Issue by pixelrebel** [jdauphant/ansible-role-nginx#126]
I'm using nginx as a reverse proxy, but I need to secure traffic to the upstream hosts.  According to [this document](https://www.nginx.com/resources/admin-guide/nginx-tcp-ssl-upstreams/), it looks like I need a `stream` configuration.  I've tried setting this up with this role, but I'm having difficulty.  Can a kind soul please point me in the right direction?

Thanks.

**Comment by jdauphant** [comment]
Hello @pixelrebel ,
You can use `nginx_stream_configs` and `nginx_stream_params ` to set stream.
In `nginx_stream_configs` you have to include `server { }` in your rules is not automatic like `nginx_sites`.

If you have difficulty to use it, show example of your config.

Best regards,
Julien

**Comment by philipwigg** [comment]
Is it an HTTP back-end service? Can you not just secure it using an HTTPS back-end instead?

**Comment by pixelrebel** [comment]
@philipwigg In one case it will be HTTP, in another case, it is TCP based protocol.  So, I think I will need to setup a config for both services.  

>Can you not just secure it using an HTTPS back-end instead?

Do you mean [this approach](https://www.nginx.com/resources/admin-guide/nginx-https-upstreams/)?  This is what I'm trying to master first before I go down the streams route.

**Comment by pixelrebel** [comment]
@jdauphant I got streams working with your role.  Thanks much for your contribution to this role!
