### ISSUE TITLE
unknown directive "auth_pam" when installed nginx with this role.

### ISSUE THREAD

**Issue by manjitkumar** [jdauphant/ansible-role-nginx#145]
2016/11/30 12:42:16 [emerg] 27990#0: unknown directive "auth_pam" in /etc/nginx/sites-enabled/docker-hub.conf:20```

"auth_pam" module comes with nginx-full, Can someone help me with installing nginx full or make changes to existing role for installing this third-party module for nginx.

**Comment by jdauphant** [comment]
You can change installed package, choose your system:
```
nginx_redhat_pkg:
  - nginx

nginx_ubuntu_pkg:
  - python-selinux
  - nginx

nginx_freebsd_pkg:
  - nginx

nginx_suse_pkg:
  - nginx
``

**Comment by manjitkumar** [comment]
@jdauphant Yes, I was able to resolve above issue with overriding 
```yml    nginx_ubuntu_pkg:
      - python-selinux
      - nginx-full```

**Comment by sar009** [comment]
I was able to solve by
```
nginx_pkgs:
  - nginx-full
```
