### ISSUE TITLE
Add stream configuration

### ISSUE THREAD

**Issue by jadjay** [jdauphant/ansible-role-nginx#160]
Streams can be add with nginx_extra_root_params, but it's not an appropriate solution, because of the leading semi-colon and the size on the line.

The best should be to add a streams configuration

**Comment by jdauphant** [comment]
There is already `nginx_stream_params` and `nginx_stream_configs`.
But it's only when nginx_official_repo_mainline is true. (https://github.com/jdauphant/ansible-role-nginx/blob/master/templates/nginx.conf.j2#L37)
We can change this condition to add the stream section if `nginx_stream_params` or `nginx_stream_configs` aren't respectively empty list and map.
A pull request will be welcome
