### ISSUE TITLE
Compiling nginx or installing from .deb/.rpm file

### ISSUE THREAD

**Issue by k1-hedayati** [jdauphant/ansible-role-nginx#171]
Hello,
Is there support for installing nginx from source or using .deb/.rpm?

**Comment by jdauphant** [comment]
Hello,
It's not supported yet.

- Feel free to suggest a pull request to add that.
- You also can install nginx outside this role and use the role only for configuration. In that case, just set the variable `nginx_installation_type` to `configuration-only`

Best regards,
Julien

**Comment by k1-hedayati** [comment]
I'm new to ansible so I can't PR unfortunately, but I think I can use second option, thank you

**Comment by megheaiulian** [comment]
@k1-hedayati : At https://github.com/plumelo/ansible-role-nginx_src I have a role that installs nginx from deb with configurable additional modules (tested only on Ubuntu xenial so far).

**Comment by k1-hedayati** [comment]
Great, so I think I can close this issue
