### ISSUE TITLE
Change nginx user

### ISSUE THREAD

**Issue by krzyzakp** [jdauphant/ansible-role-nginx#207]
We wanted to run on Debian family (Ubuntu 16.04) nginx as user nginx, not www-data as it's defined by default for this family.  We set nginx_user, but it's not working.
As I dig in, it's due to `tasks/main.yml` including vars/{os}.yml - what due to our  `hash_behaviour = true` in ansible.cfg, does hiera merge and overwrite with data from OS specific yaml file.

**Comment by jdauphant** [comment]
@krzyzakp Thanks for the report.

If you want, you can submit a PR like that : 
- in `vars/*.yml` rename all `nginx_user` in `nginx_default_user`
- add `nginx_default_user: nginx` in vars/empty.yml
- in `defaults/main.yml` change `nginx_user: nginx` to `nginx_user: "{{nginx_default_user}}"`

It should solve the problem

**Comment by jdauphant** [comment]
@krzyzakp Have you seen my message ?

**Comment by krzyzakp** [comment]
@jdauphant Yes, sorry for delay in answering. I just submitted PR with solution.

**Comment by jdauphant** [comment]
@krzyzakp We have reverted your PR, but #214 have been merged and can do that too
