### ISSUE TITLE
v2.16 missing on https://galaxy.ansible.com/jdauphant/nginx

### ISSUE THREAD

**Issue by vishesh92** [jdauphant/ansible-role-nginx#230]
v2.16 is available on [GitHub](https://github.com/jdauphant/ansible-role-nginx/releases)
but its not listed on [ansible-galaxy](https://galaxy.ansible.com/jdauphant/nginx)
Because of this I am not able to install v2.16 through ansible-galaxy.

**Comment by jdauphant** [comment]
@vishesh92 Thanks for the report, Galaxy have made a change in there import process : "v2.16" is no more accepted, I have change it to v2.16.0
