### ISSUE TITLE
add a way to include common configuration files.

### ISSUE THREAD

**Issue by jrobeson** [jdauphant/ansible-role-nginx#25]
when deploying SSL like shown in https://github.com/igrigorik/istlsfastyet.com/tree/master/nginx
you need to duplicate the ssl configuration twice between sites to make sure secure access to https://www.example.org and https://example.org are covered by the same configuration. i solved it with a quick hack like so: http://fpaste.org/163673/63848141/

and then put this in role configuration:
 - include /etc/nginx/ssl.conf

This is a pretty naive way of doing it, maybe you have a better idea.

It would be hard to automate properly as the loading order for the config files might matter, so simply processing them before or after the site inclusion might not work well for everyone.

**Comment by jrobeson** [comment]
if a host doesn't use ssl, will this cause any performance issues for them? I'm not sure how nginx deals with this, as i don't usually have a config with some ssl and some not.

**Comment by jdauphant** [comment]
The ssl_* parameters only impact if you have this line on a server {} block :

    listen port_number ssl

I always do like that and It doesn't impact non ssl config.

**Comment by jrobeson** [comment]
my other usecase for this is my app. I have two different playbooks. One for an applicance/standalone machine and another for the hosted/sass version.  They all share the same app configuration, but the hosts names, ssl availablility, and ports are all different. I'd prefer not to duplicate the same 30 line app configuration between these two different playbooks. It'd be too easy to get out of sync.

Of course, this problem would be pretty easily solved if ansible allowed a per dict instance for merging instead of only the global setting.

**Comment by jdauphant** [comment]
You can now do that with the new notation of the v1.2 :+1: 
https://github.com/jdauphant/ansible-role-nginx/releases/tag/v1.2

Thanks for your help @jrobeson
