### ISSUE TITLE
don't install SELinux related packages if SELinux is disabled

### ISSUE THREAD

**Issue by jrobeson** [jdauphant/ansible-role-nginx#28]
pretty minor issue, just figured i'd mention it though.

SELinux is disabled by default on digitalocean droplets (and similiar VPSes too probably)  to allow for resetting the root password.

**Comment by jdauphant** [comment]
It could be nice to detect this and don't install python-selinux on Debian if it's the case

**Comment by jrobeson** [comment]
the getenforce command should do it:

getenforce reports whether SELinux is enforcing, permissive, or disabled.

so if that command doesn't exist or reports Disabled  then selinux is turned off. 

It seems to be Disabled , even though the manpage says disabled

**Comment by exploide** [comment]
There already is a built-in fact which can be used to check that. Here the relevant portion of the output of the setup module:
```json
"ansible_selinux": {
    "config_mode": "enforcing", 
    "mode": "enforcing", 
    "policyvers": 30, 
    "status": "enabled", 
    "type": "targeted"
}
```

**Comment by jdauphant** [comment]
Thanks @exploide, if you can made a PR, it will be nice !

**Comment by exploide** [comment]
I will take a look when time allows it. Figured out I also have to address another SELinux related issue: Setting the `nginx_worker_rlimit_nofile` variable is forbidden unless a SELinux boolean is tweaked. Guess this can be done together.
