### ISSUE TITLE
should the generated config files be readable?

### ISSUE THREAD

**Issue by jrobeson** [jdauphant/ansible-role-nginx#29]
currently it looks like something like this:

```
$ cat conf.d/gzip.conf
#Ansible managed: ansible/vendor/roles/jdauphant.nginx/templates/config.conf.j2 modified on 2015-01-10 04:59:19 by johnny on falling

   gzip on ;   gzip_comp_level 5 ;   gzip_min_length 256 ;   gzip_proxied any ;   gzip_types application/atom+xml application/javascript application/json application/rss+xml application/vnd.ms-fontobject application/x-font-ttf application/x-web-app-manifest+json application/xhtml+xml application/xml font/opentype image/svg+xml image/x-icon text/css text/plain text/x-component ;
```
I think it should look more like this:
```
gzip on
gzip_comp_level 5; 
gzip_min_length 256;
gzip_proxied any;
gzip_types application/atom+xml application/javascript application/json application/rss+xml application/vnd.ms-fontobject application/x-font-ttf application/x-web-app-manifest+json application/xhtml+xml application/xml font/opentype image/svg+xml image/x-icon text/css text/plain text/x-component ;
```

**Comment by jdauphant** [comment]
For the new line, it's normaly already done :
https://travis-ci.org/jdauphant/ansible-role-nginx/builds/45886297#L783
That's strange, what is the ansible version ?

**Comment by jrobeson** [comment]
1.8.2. . I also ran into trouble with the v variable being None too. I just upgraded my remote boxes to Fedora 21.

**Comment by jrobeson** [comment]
i think i was a bit sleep deprived to totally overlook the \n's that are quite obviously there. even if they don't seem to be rendering properly.

**Comment by jdauphant** [comment]
@jrobeson can I close the ticket ?

**Comment by jrobeson** [comment]
it still effects me, but i also am not using this role anymore, since it can't handle some of the stuff i want it to do.

**Comment by jdauphant** [comment]
I was thinking to add the support for syntax like that : 
```
 bar: |
     listen 9090;
     server_name ansible;
     root "/tmp/site2";
     location / { 
           try_files $uri $uri/ /index.html; 
     }
     location /images/ {
         try_files $uri $uri/ /index.html;
         allow 127.0.0.1;
         deny all;
     }
```
In yaml "|" is a string where new lines are keeped.

What do you thinks ? this can solve some of your problems ?
