### ISSUE TITLE
map statements fail if in http configuration

### ISSUE THREAD

**Issue by jrobeson** [jdauphant/ansible-role-nginx#32]
I didn't test anywhere else yet, 

but if you try to write something like:

```
  - map $scheme $hsts_header {
         https 'max-age=10886400; includeSubDomains;'
     }
```

then it adds a ; after the } which makes the the configuration testing fail.

**Comment by jrobeson** [comment]
i tried copying and modifying the similiar logic in the other other templates
```
   {% if v != "" %}{{ v.replace(";",";\n      ").replace(" {"," {\n      ").replace(" }"," \n   }\n") }}{% if v.find('{') == -1%};
```
but that code looks like it would have problems with semicolons within strings , as there's no code to check of the semicolin is within a quoted string and thus should ignore it.

**Comment by jdauphant** [comment]
Hi @jrobeson ,
Sorry for the late response on that, you can do something like that :
```
 bar: 
   - |
     map $scheme $hsts_header {
         https 'max-age=10886400; includeSubDomains;'
     }
```
In yaml "|" is a string where new lines are keeped.
Normaly it's works but produce ugly conf.
You can test this commit that produce good conf input :
https://github.com/jdauphant/ansible-role-nginx/commit/362b995a943566a5bdcb611a9ded0deb30ec92c3
It's you see not problem with the commit, I will merge it to master.

What do you thinks ?
Thanks in advance for you anwser

**Comment by jdauphant** [comment]
I close the ticket it's now supported in the version 1.2 :
```
- |
     map $scheme $hsts_header {
         https 'max-age=10886400; includeSubDomains;'
     }
```
Thanks for your help @jrobeson

**Comment by chanon** [comment]
Sorry to comment on this old issue, but was just wondering why the `v.replace(";",";\n      ")` part is needed. A lot of http headers can have semicolons in them. 

Just as an example, after updating some things in my code base, my Content-Security-Policy started having problems and I tracked it down to the extra \n inserted in the semicolons in it.

I removed the `replace(";",";\n      ")` in my local copy, but am wondering what it is needed for.

**Comment by jdauphant** [comment]
@chanon It's for that you have a second notation: you can see a exemple of the new notation in my last message.

# Change apply to each notation
## Old notation:
```{% if v != "" %}{{ v.replace(";",";\n      ").replace(" {"," {\n      ").replace(" }"," \n   }\n") }}{% if v.find('{') == -1%};
{% endif %}{% endif %}```
## New notation:
```{{v.replace("\n","\n   ")}}```

**Comment by jdauphant** [comment]
Hey @chanon, did you get your answer in my last message ?

Also ```replace(";",";\n ")`` was introduced to have good output file.

**Comment by ElRoberto538** [comment]
I don't think this issue is resolved? The ```/templates/nginx.conf.j2``` file http block is 
```
http {
        include {{ nginx_conf_dir }}/mime.types;
        default_type application/octet-stream;
{% for v in nginx_http_params %}
        {{ v }};
{% endfor %}

        include {{ nginx_conf_dir }}/conf.d/*.conf;
        include {{ nginx_conf_dir }}/sites-enabled/*;
}
```

Which adds a semicolon to every http parameter - including the map block which will then fail as it shouldn't have a semicolon. @jrobeson seems to have suggested replacing it with the block from site.conf.j2, which I did, and it now works (unsure if it breaks in other scenarios):

```
http {
        include {{ nginx_conf_dir }}/mime.types;
        default_type application/octet-stream;
{% for v in nginx_http_params %}
    {% if v.find('\n') != -1 %}
        {{v.replace("\n","\n   ")}}
    {% else %}
        {% if v != "" %}{{ v.replace(";",";\n      ").replace(" {"," {\n      ").replace(" }"," \n   }\n") }}{% if v.find('{') == -1%};
    {% endif %}{% endif %}{% endif %}
{% endfor %}

        include {{ nginx_conf_dir }}/conf.d/*.conf;
        include {{ nginx_conf_dir }}/sites-enabled/*;
}
```

**Comment by jdauphant** [comment]
Hello @ElRoberto538 ,
It was already propose https://github.com/jdauphant/ansible-role-nginx/pull/141 .
We haven't merge it to promote "nginx_configs" variable instead.

**Comment by ElRoberto538** [comment]
@jdauphant Ah, right... Thanks for that, I don't know how I missed that. At least now there's a link for others to hopefully not make the same mistake as me!
