### ISSUE TITLE
Testing nginx_daemon_mode == "on" for start/restart/reload does not work as expected

### ISSUE THREAD

**Issue by noirbee** [jdauphant/ansible-role-nginx#44]
In the default variables file, `defaults/main.yml`:
`nginx_daemon_mode: on`

However this is interpreted as a boolean when loading YAML and thus the test always fails since it compares a regular string ("on") to a boolean (True). Hence `nginx` is never started/reloaded/restarted as needed.

I'd suggest just reverting the last two commits but since you explicitly added the ` == "on"` I suspect you had something else in mind :) Using `nginx_daemon_mode: "on"` would also work I suppose, but would lose the type information (i.e. the fact that this is actually a boolean variable).

**Comment by jdauphant** [comment]
Hi,

Thanks for the remark.
I have change the default value from nginx_daemon_mode to "on" .
It will be better if nginx_daemon_mode was a true boolean but for API compatibility, I keep the previous solution.

Have a nice day,
Julien

**Comment by jdauphant** [comment]
Corrected in v1.3.4

**Comment by jdauphant** [comment]
@noirbee If you still have the problem, don't hesitate to reopen.

Have a nice day,
Julien

**Comment by pedros007** [comment]
@jdauphant this is probably a problem with Ansible Galaxy, but when I try to install via

    ansible-galaxy install -p roles jdauphant.nginx

I get version 1.3.3 instead of the recently released 1.3.4 which addresses this issue.

**Comment by jdauphant** [comment]
Thanks @pedros007 , I just update the role on Ansible Galaxy.
