### ISSUE TITLE
Default site variables

### ISSUE THREAD

**Issue by Lorenzbi** [jdauphant/ansible-role-nginx#57]
Hi,
Maybe I just didn't find it but I can't find a way to set default site variables for all vhosts. How would I set this globally for all vhosts?

    - index index.php
    - location / { try_files $uri $uri/ /index.php; }
    - location ~ \.php$ { fastcgi_pass unix:/var/run/php5-fpm.sock; .... etc.

**Comment by jdauphant** [comment]
Hi @Lorenzbi ,

You can use ansible variables and the new role syntaxe introduce in 1.2 .
Example here :
https://github.com/jdauphant/ansible-role-nginx/releases/tag/v1.2

Best regards,
Julien

**Comment by Lorenzbi** [comment]
Thanks! This really simplifies the playbook if I have multiple vhosts.
