### ISSUE TITLE
support installation of nginx from different repo

### ISSUE THREAD

**Issue by nschloe** [jdauphant/ansible-role-nginx#65]
I would like to install nginx from the [phusion passenger repo](https://www.phusionpassenger.com/install_debian). Right now, I do this manually and set
```
nginx_installation_type
```
to something invalid (`packages_phusion`). This avoids that ansible-role-nginx installs nginx from another repository.

Unfortunately, a side effect of this setting is that nginx is not properly restarted upon config change. The respective code from `handlers/main.yml` is
```
- name: reload nginx
  service: name={{ nginx_service_name }} state=reloaded
  when: nginx_installation_type in nginx_installation_types_using_service and nginx_daemon_mode == "on"
```
(Here, the condition `nginx_installation_type in nginx_installation_types_using_service` is false.)

What could be done to fix this?

**Comment by jdauphant** [comment]
Hi @nschloe,
Thanks for the bug report.

I just introduce ```nginx_installation_type: "configuration-only"``` on 1.7 than normally solve your problem.

Best regards,
Julien

**Comment by jdauphant** [comment]
Close the ticket if this solve well your problem.

**Comment by nschloe** [comment]
Works well, thanks!
