### ISSUE TITLE
With hash behavior = merge, default site is not removed

### ISSUE THREAD

**Issue by Jonnymcc** [jdauphant/ansible-role-nginx#75]
We use hash_behavior: merge and if I specify nginx_sites in my playbook the default site gets added back in sites-available and sites-enabled. I think this can be fixed by changing the order in main.yaml to
```
- include: configuration.yml
- include: remove-defaults.yml
  when: not keep_only_specified
- include: remove-extras.yml
  when: keep_only_specified
- include: remove-unwanted.yml
```

**Comment by jdauphant** [comment]
Hello @Jonnymcc ,
Yes, we can do that.
You can propose a pull request.
Thanks
