### ISSUE TITLE
Default setup does not work on physical host

### ISSUE THREAD

**Issue by bchatelard** [jdauphant/ansible-role-nginx#78]
I have tested this role on a physical node and the generated configuration was invalid.
The nginx process was launching with 0 workers, and it hangs and cannot proceed any request.

Here is the truncated output of `ansible -m setup` for my host:

```
"ansible_processor_cores": 1,
"ansible_processor_count": 0,
"ansible_processor_threads_per_core": 1,
"ansible_processor_vcpus": 0,
```

The default configuration is using `ansible_processor_vcpus` but it looks like it is set to 0 on physical nodes. (https://github.com/jdauphant/ansible-role-nginx/blob/e37bd0538634ba0222666130f2e87a2e9f971c89/defaults/main.yml#L32)

I saw that we can enforce the number of worker in the configuration by setting the `nginx_worker_processes`.
You should consider using another property to ensure that it works out of the box for everyone.

**Comment by jdauphant** [comment]
Hi @bchatelard ,
Thanks for the report.
It's strange because I have already use this role on physical node.
We can add a condition : if ansible_processor_vcpus is 0 to use ansible_processor_cores instead.

**Comment by bchatelard** [comment]
Strange, maybe this is a specific issue related ansible facts on my server (this is an ARM server running at https://scaleway.com ).

Also, i am not sure the `"ansible_processor_count": 0,` is normal.

**Comment by bchatelard** [comment]
Yes, i think the `ansible_processor_vcpus` facts should never be 0.
https://github.com/maxamillion/ansible/blob/f274234824c8556362b9dea8516d4a5d6e44f392/lib/ansible/module_utils/facts.py#L679-L680

I believe this is an ansible fact issue.
Sorry.

**Comment by jdauphant** [comment]
ansible_processor_count should not be 0 too
