### ISSUE TITLE
ansible_processor _vcpus undifined on digital ocean FreeBSD box

### ISSUE THREAD

**Issue by mike-pt** [jdauphant/ansible-role-nginx#87]
TASK: [jdauphant.nginx | Copy the nginx configuration file] ******************* 
fatal: [www] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'ansible_processor
_vcpus' is undefined", 'failed': True}
fatal: [www] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'ansible_processor
_vcpus' is undefined", 'failed': True}

I'm using version 1.9.4 on my workstation and getting this error.

EDIT: also ansible -m setup is not returning it or anything similar, so I'm not sure if this actually is a ansible bug

**Comment by jdauphant** [comment]
It's looks like an Ansible bug.

You can define manually this variable to compensate : 
```nginx_worker_processes```

**Comment by mike-pt** [comment]
yeah thats what I did as a workaround,  ans this was reported as a bug before ans supposedly fixed(I'll paste the ghi for reference later,  on mobile now) 

but in any case not an issue on you're side so I guess it can be closed

**Comment by mike-pt** [comment]
here:
https://github.com/ansible/ansible/issues/9008

It seems the fix was reverted cause it was causing more issues, I wonder if this just affects FreeBSD or all DigitalOcean vms, If I have time I might take a peak at the code that gets this value, anyway for now I'll just edit the role and define the var to a default of "1" and increase in the playbooks if needed.

**Comment by nowayride** [comment]
Came to this from the referenced issue, FYI the root cause isn't due to an Ansible bug, though the expected output may be. You're trying to use a variable that doesn't exist. Variables can be guarded using the default() filter, and given that facts might not be available it's probably best to do so. You could either default(1) or guard against it in the template. I'd use nginx_worker_processes: "{{ ansible_processor_vcpus|default(None) }}" then use {% if nginx_worker_processes %} block in the template.

**Comment by jdauphant** [comment]
@nowayride Ok thanks, don't hesitate to submit a PR

**Comment by mike-pt** [comment]
@nowayride that sounds 100% correct.

But I'd like to add that this fact should be present on FreeBSD, I was actually looking into the code a couple of days ago but then other stuff came up, the code is just doing it wrong for FreeBSD... its looking in dmesg for string that are not present / don't reflect the cpu/threads info, or maybe it was in older versions... anyway if I get some time tomorrow I'll poke around more... looking for "SMP" in dmesg would work.

I.E.
```
% dmesg | grep SMP
FreeBSD/SMP: Multiprocessor System Detected: 4 CPUs
FreeBSD/SMP: 1 package(s) x 2 core(s) x 2 SMT threads
```

But anyway you're point is still pretty valid for any "fact"
