### ISSUE TITLE
site name as variable

### ISSUE THREAD

**Issue by mike-pt** [jdauphant/ansible-role-nginx#88]
Is it possible to use the "site name" as a variable?

I'm trying to simplify certain configs for multiple vhosts, such as access_log and error_log directives.

I.E.:

```
          example.org:
            - listen 80
            - server_name {{ site_name }}
            - access_log  /var/log/nginx/{{ site_name }}-access.log
            - error_log   /var/log/nginx/{{ sitte_name }}-error.log

```

Something like that...

Thanks

**Comment by jdauphant** [comment]
Hello,

Try with ```{{ item }}```, it could work.
It could be interesting to introduce variables into the template.

Best regards,
Julien

**Comment by mike-pt** [comment]
Yeah I've tried that but does't work from the playbook, as the "{{ item }}" variable won't be defined, I'm a bit new to ansible but that's the first thing that cross my mind... 

Probably the only way to achieve this is really introducing vars in the template as you suggest, might be a nice improvement to the role :)

**Comment by jdauphant** [comment]
Don't hesitate to submit a MR, unfortunately I don't have time to do that myself :(

You can also try this syntaxe also  (but I think I won't work either)
```
    example.org: |
            listen 80;
            server_name {{ item }};
```

**Comment by mike-pt** [comment]
Sure, I'll poke around, I wonder if there's some way to dump/see all vars in verbose mode or something...

In alternative I guess I can use global vars and re-use them in the playbook, maybe a dictionary or something, If you don't mind can we keep this open in case I find a solution (for a while ofc)

**Comment by jdauphant** [comment]
Ok I keep it open

**Comment by mike-pt** [comment]
@jdauphant I've been lookigng at this again and I was wondering if there would be a way to have example.org: set to "{{site_name}}":

Say one passes a extra var ` ansible-playbook site.yml -e "site_name=example.org"

And then we have (in the site.yml playbook):
```
nginx_sites:
        '{{site_name}}:
          - |
            listen 80;
            server_name {{site_name}} www.{{site_name}};

            access_log  "{{nginx_log_dir}}/{{site_name}}-access.log";
            error_log   "{{nginx_log_dir}}/{{site_name}}-error.log";
``` 

Something like this would be awesome cause we can have a single playbook to spin up a bunch of nginx-sites by just passing the site_name var 

But when I try to do that I get:
```
failed: [example.org] => (item={{site_name}}) => {"failed": true, "item": "{{site_name}}", "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute u'{#site_name#}'"
```

I was expecting '{{site_name}}' to use the var value, but it fails with the dic object error, and I honestly don't get why, do you have any idea?

**Comment by mike-pt** [comment]
guess this is the issue --> https://github.com/ansible/ansible/issues/9008

**Comment by jdauphant** [comment]
Sorry, no idea, I do not use as much Ansible

**Comment by philipwigg** [comment]
I don't think you can use a variable as a dictionary key.

You can certainly use a variable as the value for your ```server_name``` like you do in your first example but you'd have to define the variable as usual (i.e. in the playbook, or in group_vars, or wherever).

You can probably close this one?

**Comment by philipwigg** [comment]
Cheers. I don't think I can close this one as it's not my issue and I'm not an owner.

**Comment by mike-pt** [comment]
lol sorry I did not realise that
