### ISSUE TITLE
Yum install on el

### ISSUE THREAD

**Issue by PumpkinSeed** [jdauphant/ansible-role-nginx#93]
When I use the nginx installer on EL the code disable all repo and the it can download the dependency packages like openssl... etc. 
```
yum: name={{ item }} state=present disablerepo='*' enablerepo={{ "nginx," if nginx_official_repo else "" }}{{ yum_epel_repo }},{{ yum_base_repo }}
```
But if I allow him to use all repo it will work without problem: 

`yum: name={{ item }} state=present`

**Comment by jdauphant** [comment]
Maybe @jrobeson @etcet @victorluft or @mtotheikle can help on this issue and suggestion a solution.
An MR will be welcomed

Best

**Comment by basnijholt** [comment]
Having the same issue, trying to install `nginx` in this Dockerimage: https://hub.docker.com/r/ansible/centos7-ansible/

**Comment by aries1980** [comment]
If the Nginx repo maintainers follow the same version pattern as EL, I see no issue enabling the default repos.

**Comment by jdauphant** [comment]
We can try something like that :+1: 
```
yum: name={{ item }} state=present enablerepo={{ "nginx," if nginx_official_repo else "" }}
```
or 
```
yum: name={{ item }} state=present enablerepo={{ "nginx," if nginx_official_repo else "" }}{{ yum_epel_repo }},{{ yum_base_repo }}
```

If you have a solution that keep the possibility to use the official repo, it could be very nice.
A MR will be welcomed :)

**Comment by PumpkinSeed** [comment]
I tried the first:

`yum: name={{ item }} state=present enablerepo={{ "nginx," if nginx_official_repo else "" }}`

It is working correctly, thanks.

**Comment by jdauphant** [comment]
@PumpkinSeed Thanks, I can't test it on my side. Can you send a pull request with the tested solution ?

**Comment by PumpkinSeed** [comment]
@jdauphant Yes, I will do it asap.
