### ISSUE TITLE
Role doesn't ensure that nginx_sites exactly matches sites-enabled

### ISSUE THREAD

**Issue by steven-collins-omega** [jdauphant/ansible-role-nginx#96]
Hello, maybe I am missing something (I am not an Ansible expert), but the behavior I expected from this role was that the configured nginx sites on the host would be _exactly_ those configured under `nginx_sites`.

However, while working on a playbook using this role, at one point I decided to change the name of a site, and proceeded to make further changes. When those changes were not picked up, upon further investigation I realized that the site with the original name (which happened to be alphabetically before the new name) was still there from previous playbook runs. Presumably it was overriding the correct site, which still had the same `server_name` and was configured to listen on the same port.

**Comment by jdauphant** [comment]
It's not the case, in case you want to apply multiple time the same role on the same server;
You have an option "keep_only_specified" for that.
You have also the option "nginx_remove_sites" to remove only old configuration.

**Comment by steven-collins-omega** [comment]
Ah, I had missed "keep_only_specified", that sounds like exactly what I want. Thank you for the quick clarification.
