### ISSUE TITLE
Configured upstream does not appear in resulting config

### ISSUE THREAD

**Issue by Agnikay** [jdauphant/ansible-role-nginx#97]
I'm trying to setup nginx as load balancer using next set of variables:
```
   nginx_user: "www-data"
   nginx_sites:
    default:   
     - listen 80;
       server_name _;
       location / {
           proxy_pass http://backend;         
       }
   nginx_configs:
    upstream:
     - upstream backend { server 192.168.10.10; }
```
Config created after provisioning:
```
server {
   listen 80;
       server_name _;
       location / {
       proxy_pass http://backend;

   }
}
```
But there is no created upstream. Could you please advise how can I correctly configure it?
`Ansible version: 1.9.4`

**Comment by jdauphant** [comment]
Is this file (/etc/nginx/conf.d/upstream.conf) exists?

FYI: normally with this you can have a better output:
```
   nginx_sites:
    default:  
    -| listen 80;
       server_name _;
       location / {
           proxy_pass http://backend;         
       }
```

**Comment by Agnikay** [comment]
The file `/etc/nginx/conf.d/upstream.conf` exists, thank you. 
After i've applied statement you proposed default.conf file became next:

```
server {
   -;
   |;
    ;
   l;
   i;
   s;
   t;
   e;
   n;
    ;
   8;
   0;
   ;
      ;
    ;
   s;
   e;
   r;
   v;
   e;
   r;
   _;
   n;
   a;
   m;
   e;
    ;
   _;
   ;
      ;
    ;
   l;
   o;
   c;
   a;
   t;
   i;
   o;
   n;
    ;
   /;
    ;
   {    ;
   p;
   r;
   o;
   x;
   y;
   _;
   p;
   a;
   s;
   s;
    ;
   h;
   t;
   t;
   p;
   :;
   /;
   /;
   b;
   a;
   c;
   k;
   e;
   n;
   d;
   ;
      ;
    ;
   };
}
```

**Comment by jdauphant** [comment]
Funny output :) My mistake, I miss the new line after "|".
You have functionnal examples here : https://github.com/jdauphant/ansible-role-nginx/releases/tag/v1.2

**Comment by Agnikay** [comment]
Thank you for your time! Is it possible to move upstream file to one config with server and locations or i need to add some task to merge files?

**Comment by jdauphant** [comment]
It's not possible with the current role architecture
